logs:
	docker-compose logs
log:
	docker-compose logs
ps:
	docker-compose ps
down:
	docker-compose down
stop:
	docker-compose stop
up:
	docker-compose up -d
start:
	docker-compose start
build:
	docker-compose build
build-no-cache:
	docker-compose build --no-cache
sh-amazonlinux:
	docker-compose exec amazonlinux sh
sh:
	docker-compose exec amazonlinux sh

